### ISSUE TITLE
AfterBuy UTF8 Encoding

### ISSUE THREAD

**Issue by recompile** [FATCHIP-GmbH/plugin-oxid-oxid2afterbuy#12]
Using utf8_encode in core/fco2aorder.php line 61 in unnecessary if using

https://api.afterbuy.de/afterbuy/ShopInterfaceUTF8.aspx

as the Interface-Url.

`$sOrderarticleParameters .= "&Artikelname_{$iSuffix}=" . urlencode(utf8_encode($oOrderArticle->oxorderarticles__oxtitle->value . " " . $oOrderArticle->oxorderarticles__oxselvariant->value));`

I believe we have to make some enhancements handling utf8.

**Comment by FCStephanAltmann** [comment]
Dieses Issue wurde in unser internes Ticketsystem aufgenommen und dem zuständigen Projektleiter zugeteilt.

**Comment by FCStephanAltmann** [comment]
Solved with release 1.3.1
