### ISSUE TITLE
AfterBuy und Versandgewicht(e)

### ISSUE THREAD

**Issue by recompile** [FATCHIP-GmbH/plugin-oxid-oxid2afterbuy#13]
Es sollte eine Möglichkeit geben beim Uebtragen der Bestellung an AfterBuy das Versandgewicht zu ueberschreiben.

Die Versandgewichte sind im Shop bei den Artikeln hinterlegt und werden an das AfterBuy API uebertragen 'ArtikelGewicht_{$iSuffix}').

Grund: Wenn das Versandgewicht 31,5 Kg ueberschreitet verweigert AfterBuy den Druck von Paketscheinen (zu Recht).

Z.Z. versuche ich das zu umgehen indem ich 'ArtikelGewicht_{$iSuffix}' alle auf '0,1' setze. Dann wird
auf dem Paketschein immer ein falsches Gewicht angegeben.

**Comment by FCStephanAltmann** [comment]
Das Issue wurde in unser Ticketsystem aufgenommen und dem zuständigen Projektleiter zugeteilt.

**Comment by andrefatchip** [comment]
Solved in https://github.com/FATCHIP-GmbH/plugin-oxid-oxid2afterbuy/pull/29
