### ISSUE TITLE
Article stocks are not always reduced when importing orders

### ISSUE THREAD

**Issue by weberdigital** [FATCHIP-GmbH/plugin-oxid-oxid2afterbuy#52]
Steps to reproduce:

1. In the module settings set "Leading System: OXID-eShop".
1. Export articles from OXID to Afterbuy using the module.
1. In our case we list the articles in eBay using Afterbuy and place an order in eBay.
1. Import the eBay order from Afterbuy to OXID using the module.

**Result:** The article stock is not reduced.

**Additional information:** We also have the special case, that we have multiple articles in OXID with the same article number. The module doesn't handle this correctly, because the modules maps the Afterbuy order positions to the OXID articles using the article number and not the article oxid. This has to be fixed, because OXID doesn't forbid using the same article number for multiple articles. We know using the same article number for multiple articles isn't quite optimal, but in our case it is required.

**Comment by weberdigital** [comment]
When will this get fixed? Without this fixed, we can't use the module and Afterbuy.

**Comment by weberdigital** [comment]
When will this get fixed? We reported this issue almost 3 months ago, and we can't use Afterbuy properly because of this.

Would you please tell us, when you will take a look at this?

**Comment by FATCHIP-GmbH** [comment]
Fixed in version 1.7.2
